name: Generate XMLTV 7 Days

on:
schedule:
- cron: "0 3 * * *"
workflow_dispatch:

permissions:
contents: write

jobs:
build:
runs-on: ubuntu-latest

steps:
  # مهم جدًا لحل مشاكل push
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0

  # إعداد بايثون
  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.x"

  # تشغيل السكربت
  - name: Run generator
    run: python epg.py

  # رفع التحديث بشكل آمن
  - name: Commit and push
    run: |
      git config user.name "epg-bot"
      git config user.email "bot@github.com"

      git add epg.xml

      git commit -m "update epg 7 days" || exit 0

      git push origin HEAD:${{ github.ref_name }}
